sonar.projectKey=muhammadhamadrafique-1
sonar.organization=MuhammadHamadRafique
sonar.projectName=Online Examination System
sonar.sources=oes,main.py
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
